  <?php
        foreach($count as $counter){
          $page=$counter['count(*)']/5;
         $_SESSION['list']='';
          for($i=0; $i<$page; $i++){
            $_SESSION['list']=$_SESSION['list']."    <sitemap>\n        <loc>".base_url()."post-sitemap".($i+1).".xml</loc>\n    </sitemap>\n";
          }
        }
  ?>
    <?php
 $count=0;
 $_SESSION['xml']='';
 foreach($blog as $blogdata){
   $count=$count+1;
   $_SESSION['xml']=$_SESSION['xml']."<url><loc>".base_url()."admin/library/frontend/single_blog/".$blogdata['id']."</loc><news:news><news:publication><news:name>The Biz Solutions</news:name><news:language>en</news:language></news:publication><news:publication_date>".$blogdata['date_']."T".$blogdata['time_'].":00+00:00</news:publication_date><news:title>".$blogdata['url']."</news:title><news:keywords></news:keywords></news:news></url>";
    }?>
 <?php 
             $myfile = fopen("sitemap-news.xml", "w") or die("Unable to open file!");
$txt = "<?xml version='1.0' encoding='UTF-8'?><urlset xmlns='http://www.sitemaps.org/schemas/sitemap/0.9' 
        xmlns:news='http://www.google.com/schemas/sitemap-news/0.9'>\n".$_SESSION['xml']."</urlset>
<!--
Performance optimized by W3 Total Cache. Learn more: https://www.w3-edge.com/products/

Page Caching using disk: enhanced (Requested URI contains query) 

Served from: guruobserver.com @ 2020-01-03 16:56:20 by W3 Total Cache
-->";
fwrite($myfile, $txt);
fclose($myfile);
   ?>
    <?php 
         $myfile = fopen("sitemap.xml", "w") or die("Unable to open file!");
$txt = "<?xml version='1.0' encoding='UTF-8'?>\n\n<!-- Sitemap file 'sitemap' statically generated by All in One SEO Pack 3.3.4 by Michael Torbert of Semper Fi Web Design on Fri, 03 Jan 2020 10:35:29 UTC -->\n<sitemapindex xmlns='http://www.sitemaps.org/schemas/sitemap/0.9'>\n".$_SESSION['list']."\n</sitemapindex>";
fwrite($myfile, $txt);
fclose($myfile);
       ?>
   <?php 
          $coun_t=0;
          $da_ta='';
          $counte_r=1;
          $c=1;
          foreach($sitemap as $list){
            $da_ta=$da_ta."<url>
            <loc>".base_url()."home/single_blog/".$list['id']."</loc>
            <lastmod>".$list['date_']."T".$list['time_'].":00Z</lastmod>
            <changefreq>yearly</changefreq>
            <priority>0.1</priority>
          </url>";
            $coun_t=$coun_t+1;
            //echo "<script>alert('".$_SESSION['blog_count']."');</script>";
            if($coun_t==5 || $c==$_SESSION['blog_count']){
              $myfile = fopen("post-sitemap".$counte_r.".xml", "w") or die("Unable to open file!");
              $txt = "<?xml version='1.0' encoding='UTF-8'?>

              <!-- Sitemap file 'post-sitemap1' statically generated by All in One SEO Pack 3.3.4 by Michael Torbert of Semper Fi Web Design on Fri, 03 Jan 2020 10:35:29 UTC -->
               <urlset xmlns='http://www.sitemaps.org/schemas/sitemap/0.9'
                xmlns:image='http://www.google.com/schemas/sitemap-image/1.1'>".$da_ta."</urlset>";
              fwrite($myfile, $txt);
              fclose($myfile);
              $coun_t=0;
              $da_ta='';
              $counte_r=$counte_r+1;
            }
             $c=$c+1;
          }
         ?>
    <?php
      echo $_SESSION['preview'];
      echo "<br>".$_SESSION['preview_url'];
      if($_SESSION['preview']=='y'){
      $text = strtolower($_SESSION['preview_url']);
  $text = str_replace(' ', '_', $text);
 $text = preg_replace('/[^a-z0-9]+/', '-', strtolower($text));
$text = str_replace("'", '', $text);
$text = preg_replace('/-{2,}/','-',$text);
$text = ltrim($text, '-'); 
$text=rtrim($text, '-');
redirect(base_url().$text);
      }else{  
     
    
  if($_SESSION['page']=='blog_add'){
      redirect(base_url()."admin/blog_edit");
  }
  if($_SESSION['page']=='blog_edit'){
   
 redirect($_SESSION['redirectURL']);

  }

}
  ?>
  